### ISSUE TITLE
 ValueError: bad marshal data (unknown type code)

### ISSUE THREAD

**Issue by varrella** [upgrados/Deep_learning_Reproduction#1]
hello!!  when I ran "python train_crfnet.py --config configs/default.cfg", I got an error like :

Initializing data generator: / |#                                                                                                                                       oading model, this may take a second...
Traceback (most recent call last):
  File "/home/ZT/anaconda3/envs/crfnet2/lib/python3.8/site-packages/keras/utils/generic_utils.py", line 231, in func_load
    code = marshal.loads(raw_code)
ValueError: bad marshal data (unknown type code)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train_crfnet.py", line 423, in <module>
    main()
  File "train_crfnet.py", line 307, in main
    model            = architectures.load_model(cfg.load_model, backbone_name=cfg.network)
  File "/home/ZT/ZT_Project/crfnet/../crfnet/model/architectures/__init__.py", line 85, in load_model
    return keras.models.load_model(filepath, custom_objects=backbone(backbone_name).custom_objects)
  File "/home/ZT/anaconda3/envs/crfnet2/lib/python3.8/site-packages/keras/engine/saving.py", line 419, in load_model
    model = _deserialize_model(f, custom_objects, compile)
  File "/home/ZT/anaconda3/envs/crfnet2/lib/python3.8/site-packages/keras/engine/saving.py", line 225, in _deserialize_model
    model = model_from_config(model_config, custom_objects=custom_objects)
  File "/home/ZT/anaconda3/envs/crfnet2/lib/python3.8/site-packages/keras/engine/saving.py", line 458, in model_from_config
    return deserialize(config, custom_objects=custom_objects)
  File "/home/ZT/anaconda3/envs/crfnet2/lib/python3.8/site-packages/keras/layers/__init__.py", line 52, in deserialize
    return deserialize_keras_object(config,
  File "/home/ZT/anaconda3/envs/crfnet2/lib/python3.8/site-packages/keras/utils/generic_utils.py", line 142, in deserialize_keras_object
    return cls.from_config(
  File "/home/ZT/anaconda3/envs/crfnet2/lib/python3.8/site-packages/keras/engine/network.py", line 1022, in from_config
    process_layer(layer_data)
  File "/home/ZT/anaconda3/envs/crfnet2/lib/python3.8/site-packages/keras/engine/network.py", line 1007, in process_layer
    layer = deserialize_layer(layer_data,
  File "/home/ZT/anaconda3/envs/crfnet2/lib/python3.8/site-packages/keras/layers/__init__.py", line 52, in deserialize
    return deserialize_keras_object(config,
  File "/home/ZT/anaconda3/envs/crfnet2/lib/python3.8/site-packages/keras/utils/generic_utils.py", line 142, in deserialize_keras_object
    return cls.from_config(
  File "/home/ZT/anaconda3/envs/crfnet2/lib/python3.8/site-packages/keras/layers/core.py", line 735, in from_config
    function = func_load(config['function'], globs=globs)
  File "/home/ZT/anaconda3/envs/crfnet2/lib/python3.8/site-packages/keras/utils/generic_utils.py", line 235, in func_load
    code = marshal.loads(raw_code)
ValueError: bad marshal data (unknown type code)

so... how to solve it?

**Comment by 191334391** [comment]
are you solve this? i have the problem too

**Comment by upgrados** [comment]
I'm sorry if I don't respond fast (or at all). This project was a very long time ago and I do remember having a lot of trouble fixing a lot of problems. I do not remember having this problem.

Please do make sure to run the correct versions, I do know that any deviations from the versions often caused more problems. So make sure you use tensorflow2.4.1 and python 3.8. It might help to also use the exact linux version we used (Linux Ubuntu 20.04).

It seems this problem occurs due to tensorflow, so I would advise to use 2.4.1 as this was the version that worked for us. If that does not work, I personally can't help you as the knowledge of this project has mostly left me and I am quite busy pursuing other "ventures"
